create table profiles (
  id uuid references auth.users primary key,
  username text unique,
  avatar_url text
);

create table scores (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users not null,
  score      integer not null,
  created_at timestamp with time zone default now()
);

-- RLS
alter table scores enable row level security;

create policy "Users can insert own score"
  on scores for insert
  with check (auth.uid() = user_id);

create policy "Everyone can read scores"
  on scores for select
  using (true);